name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        working-directory: backend
        run: npm install --production

      - name: Crear archivo .env
        run: |
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo CLIENT_URL=${{ secrets.CLIENT_URL }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env

      - name: Deploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.BACKEND_WEBSITE_NAME }}
          server-computer-name: ${{ secrets.BACKEND_SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.BACKEND_SERVER_USERNAME }}
          server-password: ${{ secrets.BACKEND_SERVER_PASSWORD }}
